#!/bin/bash

# Configuration builder for nix-me
# Generates machine configs and updates flake.nix

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/ui.sh"

# Generate machine config with multiple profiles
generate_machine_config_multi_profile() {
    local hostname="$1"
    local machine_type="$2"
    local machine_name="$3"
    local username="$4"
    local repo_dir="$5"
    shift 5
    local profiles=("$@")  # Remaining args are profiles

    print_info "Generating configuration for $hostname"
    if [ ${#profiles[@]} -gt 0 ]; then
        print_info "Profiles: ${profiles[*]}"
    else
        print_info "Profiles: (minimal base)"
    fi

    # Create machine-specific directory
    local host_dir="$repo_dir/hosts/machines/$hostname"

    if [ -d "$host_dir" ]; then
        print_warn "Host directory already exists: $host_dir"
        if ! ask_yes_no "Overwrite existing configuration?" "n"; then
            print_info "Keeping existing configuration"
            # Still update flake.nix entry
            update_flake_multi_profile "$repo_dir" "$hostname" "$machine_type" "$machine_name" "$username" "${profiles[@]}"
            return 0
        fi
    fi

    mkdir -p "$host_dir"

    # Generate host config
    cat > "$host_dir/default.nix" << EOF
{ pkgs, config, lib, ... }:

{
  # Machine-specific configuration for $hostname
  # Machine type: $machine_type
  # Generated by nix-me setup wizard

  imports = [
    # Import machine type base configuration
    ../../types/$machine_type/default.nix
  ];

  # Machine-specific customizations
  # Profiles are configured in flake.nix extraModules

  # Add any machine-specific overrides here:
  # apps = {
  #   useBaseLists = true;
  #
  #   casksToAdd = [
  #     # Machine-specific apps
  #   ];
  #
  #   casksToRemove = [
  #     # Apps to exclude on this machine
  #   ];
  # };

  # Machine-specific system settings
  # system.defaults = {
  #   # Override settings here
  # };
}
EOF

    print_success "Created host config: $host_dir/default.nix"

    # Update flake.nix
    update_flake_multi_profile "$repo_dir" "$hostname" "$machine_type" "$machine_name" "$username" "${profiles[@]}"
}

# Update flake.nix with multi-profile support
update_flake_multi_profile() {
    local repo_dir="$1"
    local hostname="$2"
    local machine_type="$3"
    local machine_name="$4"
    local username="$5"
    shift 5
    local profiles=("$@")

    local flake_file="$repo_dir/flake.nix"

    # Check if machine already exists
    if grep -q "\"$hostname\" =" "$flake_file"; then
        print_warn "Machine '$hostname' already exists in flake.nix"
        if ! ask_yes_no "Update existing entry?" "n"; then
            return 0
        fi
        # For now, just warn - proper update would require parsing
        print_info "Please manually update the entry in flake.nix"
        return 0
    fi

    # Build extraModules section
    local extra_modules=""
    if [ ${#profiles[@]} -gt 0 ]; then
        extra_modules="        extraModules = ["
        for profile in "${profiles[@]}"; do
            extra_modules+="\n          ./hosts/profiles/${profile}.nix"
        done
        extra_modules+="\n        ];"
    fi

    # Create the machine definition
    local machine_def
    if [ -n "$extra_modules" ]; then
        machine_def="        \"$hostname\" = mkDarwinSystem {
          hostname = \"$hostname\";
          machineType = \"$machine_type\";
          machineName = \"$machine_name\";
          username = \"$username\";
$(echo -e "$extra_modules")
        };"
    else
        machine_def="        \"$hostname\" = mkDarwinSystem {
          hostname = \"$hostname\";
          machineType = \"$machine_type\";
          machineName = \"$machine_name\";
          username = \"$username\";
        };"
    fi

    # Show and attempt to add
    echo ""
    print_header "Flake Configuration"
    echo ""
    print_info "Adding machine to flake.nix:"
    echo ""
    echo "$machine_def"
    echo ""

    if ask_yes_no "Add to flake.nix automatically?" "y"; then
        cp "$flake_file" "$flake_file.backup"
        print_info "Created backup: $flake_file.backup"

        # Find insertion point - before the example configurations section
        local insert_line=$(grep -n "# ===.*Multi-profile\|# ===.*Profile-based\|# ===.*examples" "$flake_file" | head -1 | cut -d: -f1)

        if [ -n "$insert_line" ]; then
            # Insert before the examples section
            {
                head -n $((insert_line - 2)) "$flake_file"
                echo ""
                echo "$machine_def"
                echo ""
                tail -n +$((insert_line - 1)) "$flake_file"
            } > "$flake_file.new"
            mv "$flake_file.new" "$flake_file"
            print_success "Added machine to flake.nix"
        else
            # Fall back to finding darwinConfigurations closing brace
            local config_line=$(grep -n "darwinConfigurations = {" "$flake_file" | cut -d: -f1)
            if [ -n "$config_line" ]; then
                # Find closing brace
                local end_line=$(tail -n +$config_line "$flake_file" | grep -n "^      };" | head -1 | cut -d: -f1)
                if [ -n "$end_line" ]; then
                    end_line=$((config_line + end_line - 1))
                    {
                        head -n $((end_line - 1)) "$flake_file"
                        echo ""
                        echo "$machine_def"
                        tail -n +$end_line "$flake_file"
                    } > "$flake_file.new"
                    mv "$flake_file.new" "$flake_file"
                    print_success "Added machine to flake.nix"
                else
                    print_warn "Could not find insertion point"
                    save_config_to_file "$repo_dir" "$hostname" "$machine_def"
                fi
            else
                print_warn "Could not find darwinConfigurations"
                save_config_to_file "$repo_dir" "$hostname" "$machine_def"
            fi
        fi
    else
        save_config_to_file "$repo_dir" "$hostname" "$machine_def"
    fi
}

# Save config to file for manual addition
save_config_to_file() {
    local repo_dir="$1"
    local hostname="$2"
    local machine_def="$3"

    echo "$machine_def" > "$repo_dir/machine-config-$hostname.txt"
    print_info "Configuration saved to: machine-config-$hostname.txt"
    print_info "Add this to your flake.nix darwinConfigurations section"
}

# Legacy function for backward compatibility
generate_machine_config_with_profile() {
    local hostname="$1"
    local machine_type="$2"
    local machine_name="$3"
    local username="$4"
    local profile="$5"
    local repo_dir="${6:-${HOME}/.config/nixpkgs}"

    # Convert single profile to array
    local profiles=()
    if [ "$profile" != "minimal" ] && [ "$profile" != "custom" ] && [ -n "$profile" ]; then
        profiles=("$profile")
    fi

    generate_machine_config_multi_profile \
        "$hostname" \
        "$machine_type" \
        "$machine_name" \
        "$username" \
        "$repo_dir" \
        "${profiles[@]}"
}

# Original function for backward compatibility
generate_machine_config() {
    local hostname="$1"
    local machine_type="$2"
    local machine_name="$3"
    local username="$4"
    local repo_dir="${5:-${HOME}/.config/nixpkgs}"

    generate_machine_config_multi_profile \
        "$hostname" \
        "$machine_type" \
        "$machine_name" \
        "$username" \
        "$repo_dir"
}

# Helper functions for package management
add_to_homebrew_casks() {
    local cask_name="$1"
    local config_file="${HOME}/.config/nixpkgs/modules/darwin/apps/installations.nix"

    print_info "To add $cask_name:"
    print_info "Edit your host config or profile and add to casksToAdd"
    echo ""
    echo "  casksToAdd = ["
    echo "    \"$cask_name\""
    echo "  ];"

    return 0
}

add_to_nix_packages() {
    local package_name="$1"

    print_info "To add $package_name:"
    print_info "Edit your host config or profile and add to systemPackagesToAdd"
    echo ""
    echo "  systemPackagesToAdd = ["
    echo "    \"$package_name\""
    echo "  ];"

    return 0
}
